# -*- coding: utf-8 -*-
"""cxr-final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BgN3uHPqTS0P0su8hrt0V0zgeaVdTKRT
"""

import os
import shutil
import subprocess

# Make Kaggle directory
os.makedirs('/root/.kaggle', exist_ok=True)

# Move API key to the correct location
shutil.copy('/content/kaggle.json', '/root/.kaggle/kaggle.json')
os.chmod('/root/.kaggle/kaggle.json', 0o600)

# Install Kaggle CLI
subprocess.run(['pip', 'install', 'kaggle'])

# Download the dataset
subprocess.run([
    'kaggle', 'datasets', 'download',
    '-d', 'paultimothymooney/chest-xray-pneumonia',
    '--force'
])

# Unzip the dataset
import zipfile
with zipfile.ZipFile('chest-xray-pneumonia.zip', 'r') as z:
    z.extractall()

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_gen = ImageDataGenerator(rescale=1./255).flow_from_directory(
    'chest_xray/train', target_size=(224,224), batch_size=32, class_mode='binary')

val_gen = ImageDataGenerator(rescale=1./255).flow_from_directory(
    'chest_xray/val', target_size=(224,224), batch_size=32, class_mode='binary')

test_gen = ImageDataGenerator(rescale=1./255).flow_from_directory(
    'chest_xray/test', target_size=(224,224), batch_size=32, class_mode='binary')

base = tf.keras.applications.MobileNetV2(
    input_shape=(224,224,3), include_top=False, weights='imagenet'
)
base.trainable = False

model = tf.keras.Sequential([
    base,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train (for demo, just 3 epochs; increase as needed for better results)
history = model.fit(train_gen, validation_data=val_gen, epochs=3)

loss, acc = model.evaluate(test_gen)
print(f"Test accuracy: {acc:.2%}")

model.save('cxr_pneumonia_model.keras')